# Generated by Django 4.2.4 on 2023-09-17 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='网站分类名称')),
                ('order_num', models.IntegerField(default=99, help_text='序号可以用来调整顺序，越小越靠前', verbose_name='序号')),
                ('icon', models.CharField(blank=True, default='fa fa-link', max_length=50, null=True, verbose_name='图标')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='推送时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '工具分类',
                'verbose_name_plural': '工具分类',
                'ordering': ['order_num', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ToolLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='网站名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='网站描述')),
                ('link', models.URLField(blank=True, null=True, verbose_name='网站链接')),
                ('order_num', models.IntegerField(blank=True, default=99, help_text='序号可以用来调整顺序，越小越靠前', null=True, verbose_name='序号')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='推送时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tool.toolcategory', verbose_name='网站分类')),
            ],
            options={
                'verbose_name': '推荐工具',
                'verbose_name_plural': '推荐工具',
                'ordering': ['order_num', 'id'],
            },
        ),
    ]
