# Generated by Django 4.2.4 on 2023-09-17 10:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SysLogsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(blank=True, max_length=32, null=True)),
                ('log_level', models.CharField(blank=True, default='info', max_length=8, null=True)),
                ('log_title', models.CharField(blank=True, max_length=255, null=True)),
                ('req_ip', models.CharField(blank=True, max_length=64, null=True, verbose_name='操作IP')),
                ('req_address', models.CharField(blank=True, max_length=64, null=True, verbose_name='地址')),
                ('req_agent', models.CharField(blank=True, max_length=512, null=True)),
                ('req_browser', models.CharField(blank=True, max_length=255, null=True)),
                ('req_system', models.CharField(blank=True, max_length=32, null=True)),
                ('req_url', models.CharField(blank=True, max_length=255, null=True)),
                ('req_method', models.CharField(blank=True, max_length=8, null=True)),
                ('req_params', models.TextField(blank=True, null=True, verbose_name='操作提交的数据')),
                ('time_out', models.IntegerField(blank=True, null=True, verbose_name='执行时间')),
                ('exception', models.TextField(blank=True, null=True, verbose_name='异常信息')),
                ('create_by', models.CharField(blank=True, max_length=255, null=True, verbose_name='创建人')),
                ('update_by', models.CharField(blank=True, max_length=255, null=True)),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='逻辑删除')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '系统-日志表',
                'verbose_name_plural': '系统-日志表',
                'db_table': 'sys_logs',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SysSetting',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='项目')),
                ('value', models.TextField(blank=True, null=True, verbose_name='内容')),
                ('types', models.CharField(default='basic', max_length=10, verbose_name='类型')),
                ('note', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除')),
                ('create_time', models.DateTimeField(auto_now=True, null=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 'sys_setting',
                'ordering': ['-create_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImageGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(default='默认分组', max_length=50, verbose_name='图片分组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '图片分组',
                'verbose_name_plural': '图片分组',
                'db_table': 'image_group',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_path', models.CharField(max_length=250, verbose_name='图片路径')),
                ('file_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='图片名称')),
                ('remark', models.CharField(blank=True, default='图片描述', max_length=250, null=True, verbose_name='图片备注')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='system_app.imagegroup', verbose_name='图片分组')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '素材图片',
                'verbose_name_plural': '素材图片',
                'db_table': 'image',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(default='myFile_附件.zip', max_length=200, verbose_name='附件名')),
                ('file_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='附件大小')),
                ('file_path', models.FileField(upload_to='attachment/%Y/%m/', verbose_name='附件')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '附件管理',
                'verbose_name_plural': '附件管理',
                'db_table': 'attachment',
            },
        ),
    ]
