# Generated by Django 4.2.4 on 2023-09-17 10:29

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutBlog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('body', models.TextField(verbose_name='About 内容')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': 'About',
                'verbose_name_plural': 'About',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250, verbose_name='文章标题')),
                ('summary', models.TextField(blank=True, default='文章摘要等同于网页description内容，请务必填写...', max_length=250, null=True, verbose_name='文章摘要')),
                ('parent_doc', models.IntegerField(default=0, verbose_name='上级文档')),
                ('sort', models.IntegerField(default=9999, verbose_name='排序')),
                ('body', models.TextField(blank=True, null=True, verbose_name='文章内容')),
                ('pre_content', models.TextField(blank=True, null=True, verbose_name='编辑内容')),
                ('editor_mode', models.IntegerField(default=1, verbose_name='编辑器模式')),
                ('img_link', imagekit.models.fields.ProcessedImageField(blank=True, default='article/default/default.png', help_text='上传图片大小建议使用5:3的宽高比，为了清晰度原始图片宽度应该超过250px', null=True, upload_to='article/upload/%Y/%m/%d/', verbose_name='封面图')),
                ('views', models.IntegerField(blank=True, default=0, null=True, verbose_name='阅览量')),
                ('slug', models.SlugField(blank=True, default='xKCIQ4jCVf3', help_text='短网址', null=True, unique=True)),
                ('is_top', models.BooleanField(blank=True, default=False, null=True, verbose_name='置顶')),
                ('is_publish', models.BooleanField(blank=True, default=True, null=True, verbose_name='是否发布')),
                ('status', models.IntegerField(choices=[(0, 0), (1, 1)], default=1, verbose_name='文档状态')),
                ('open_children', models.BooleanField(default=False, verbose_name='展开下级目录')),
                ('show_children', models.BooleanField(default=False, verbose_name='显示下级文档')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '文章',
                'verbose_name_plural': '文章',
                'ordering': ['-create_date'],
            },
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(help_text='编号决定图片播放的顺序，图片不要多于5张', verbose_name='编号')),
                ('title', models.CharField(blank=True, help_text='标题可以为空', max_length=20, null=True, verbose_name='标题')),
                ('content', models.CharField(max_length=80, verbose_name='描述')),
                ('img_url', models.CharField(max_length=200, verbose_name='图片地址')),
                ('url', models.CharField(default='#', help_text='图片跳转的超链接，默认#表示不跳转', max_length=200, verbose_name='跳转链接')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '图片轮播',
                'verbose_name_plural': '图片轮播',
                'ordering': ['number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='文章分类')),
                ('slug', models.SlugField(default='IJuijUbv29e', unique=True)),
                ('description', models.TextField(blank=True, default='分类描述', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, null=True, verbose_name='描述')),
                ('visitor', models.IntegerField(blank=True, default=1, null=True, verbose_name='浏览次数')),
                ('sort_field', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='排序方式')),
                ('is_top', models.BooleanField(default=False, verbose_name='是否置顶')),
                ('role', models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3)], default=0, verbose_name='文集权限')),
                ('role_value', models.TextField(blank=True, null=True, verbose_name='文集权限值')),
                ('icon', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='文集图标')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='网站名称')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='网站描述')),
                ('link', models.URLField(blank=True, help_text='请填写http或https开头的完整形式地址', null=True, verbose_name='友链地址')),
                ('logo', imagekit.models.fields.ProcessedImageField(blank=True, default='friend/default/default.png', help_text='上传图片大小建议120x120以上，使用友联域名命名，如tendcode.com.png', null=True, upload_to='friend/upload/%Y', verbose_name='网站LOGO')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否有效')),
                ('is_show', models.BooleanField(default=False, verbose_name='是否展示')),
                ('not_show_reason', models.CharField(blank=True, max_length=50, null=True, verbose_name='禁用原因')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接',
                'ordering': ['create_date'],
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='文章关键词')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '关键词',
                'verbose_name_plural': '关键词',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Silian',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('badurl', models.CharField(help_text='注意：地址是以http开头的完整链接格式', max_length=200, verbose_name='死链地址')),
                ('remark', models.CharField(blank=True, max_length=50, null=True, verbose_name='死链说明')),
                ('add_date', models.DateTimeField(auto_now_add=True, verbose_name='提交日期')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '死链',
                'verbose_name_plural': '死链',
                'ordering': ['-add_date'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, verbose_name='文章标签')),
                ('slug', models.SlugField(default='dvULQvCYgR0', unique=True)),
                ('description', models.TextField(blank=True, default='标签描述', help_text='用来作为SEO中description,长度参考SEO标准', max_length=240, null=True, verbose_name='描述')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='修改时间')),
                ('is_delete', models.BooleanField(blank=True, default=False, null=True, verbose_name='删除标记')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('side', models.CharField(choices=[('L', '左边'), ('R', '右边')], default='L', max_length=1, verbose_name='位置')),
                ('star_num', models.IntegerField(choices=[(1, '1颗星'), (2, '2颗星'), (3, '3颗星'), (4, '4颗星'), (5, '5颗星')], default=3, verbose_name='星星个数')),
                ('icon', models.CharField(default='fa fa-pencil', max_length=50, verbose_name='图标')),
                ('icon_color', models.CharField(choices=[('primary', '基本-蓝色'), ('success', '成功-绿色'), ('info', '信息-天蓝色'), ('warning', '警告-橙色'), ('danger', '危险-红色')], default='info', max_length=20, verbose_name='图标颜色')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('update_date', models.DateTimeField(verbose_name='更新时间')),
                ('content', models.TextField(verbose_name='主要内容')),
            ],
            options={
                'verbose_name': '时间线',
                'verbose_name_plural': '时间线',
                'ordering': ['-update_date'],
            },
        ),
    ]
